build: off
version: "{build}"

environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "8"
    - nodejs_version: "10"
    - nodejs_version: "11"
    - nodejs_version: "12"

matrix:
  fast_finish: true

cache:
  - '%APPDATA%\npm-cache -> package-lock.json'
  - node_modules -> package-lock.json

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - npm run coverage
