version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

        environment:
            COVERALLS_SERVICE_NAME: "circleci"

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v0-dependencies-{{ checksum "package-lock.json" }}
          - v0-dependencies-
      - restore_cache:
          keys:
          - sonar-cache

      - run: npm install

      - save_cache:
          paths:
            - node_modules
            - ~/.npm
          key: v0-dependencies-{{ checksum "package-lock.json" }}
        
      - run: 
          name: coverage
          command: npm run coverage
    
      - run:
          name: Push coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash) || true